# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Comigo"
license = "MIT"
licenselink = "https://github.com/gftsantana/comigo/blob/master/LICENSE.md"
description = "A simple webcomics theme for Hugo."
homepage = "https://github.com/gftsantana/comigo"
tags = ["comics", "webcomics", "minimalist", "simple"]
features = ["", ""]
min_version = 0.14

[author]
  name = "Gildo Santana"
  homepage = "https://github.com/gftsantana"
